version: "3"

services:
  web:
    build: web/
    ports:
      - "80:8000"
    depends_on:
      - "app"
  app:
    build: .
    container_name: app
    env_file: .env
    ports:
      - "8001:8001"
